### ISSUE TITLE
Change RNLoadingButton class' access control

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [souzainf3/RNLoadingButton-Swift#13]
Hi

Thanks for open sourcing this library. I have a small change request.

I have subclassed the `RNLoadingButton` to add some of my own customizations. Since Swift 3, I cannot use that class due to the following error.

> Cannot inherit from non-open class 'RNLoadingButton' outside of its defining module

Apparently this is because you cannot inherit from a class even if the base class is set to `public` in Swift 3. It has to be `open`.

Can you please `open` the `RNLoadingButton` class?

Thanks!

**Comment by souzainf3** [comment]
Hi @Isuru-Nanayakkara 

Thanks for report. I will make the suggested changes.

**Comment by Isuru-Nanayakkara** [comment]
I checked your [source](https://github.com/souzainf3/RNLoadingButton-Swift/blob/master/RNLoadingButton/RNLoadingButton.swift). And it seems the class is already has the access control `open`. But for some reason when I integrate it to my project via CocoaPods, it gets an old version which still has `public`. Maybe you forgot tp update the podspec file or something?

This is what I have in my `Podfile`.
```
platform :ios, '9.0'

target 'rnlbutton' do
  use_frameworks!

  pod 'RNLoadingButton-Swift', '4.0'

end
```

I also cleared the CocoaPods local cache plus the local specs and tried but still the same result.

**Comment by Isuru-Nanayakkara** [comment]
I sifted through your commits. It does seem to be the case.

In this [commit](https://github.com/souzainf3/RNLoadingButton-Swift/commit/ba9736d28680e06440e9b96f68f76f6def9fe17a), you had updated the library's version to 4.0 in the podspec file. But the access control is still `public`.

In the [pull request](https://github.com/souzainf3/RNLoadingButton-Swift/commit/3e8bb75485659bcb2fb3659c7e8485b1e21d1a72) you had merged, it's changed to `open` but the podspec file hasn't been updated. So `pod install` still pulls the old version of the source.

**Comment by souzainf3** [comment]
Hi,

I'm updated version to [4.0.1](https://github.com/souzainf3/RNLoadingButton-Swift/tree/4.0.1) fixing it.

A tip, you can use your pod dependencies from a branch.

```
pod 'RNLoadingButton-Swift', :git => 'https://github.com/souzainf3/RNLoadingButton-Swift.git', :branch => 'master'

```

**Comment by Isuru-Nanayakkara** [comment]
Thanks! All good now.
