### ISSUE TITLE
Using hideTextWhenLoading when UIButton's title is attributed

### ISSUE THREAD

**Issue by LHIOUI** [souzainf3/RNLoadingButton-Swift#14]
hi @souzainf3 thank you for this awesome pod. I have an issue using the RNLoadingButton that
when using hideTextWhenLoading  with an attributed title button text doesn't hide. So we should basically test if the button have a title or an attributed title.

**Comment by souzainf3** [comment]
Hi @LHIOUI 

Thanks for your observation. The actual version don't contemplate attributed title.

So they were free for that change. It would be a pleasure to receive a pull request. :-)

**Comment by souzainf3** [comment]
Thanks @LHIOUI for your pull request. The new version 4.0.2 is uploaded.
