### ISSUE TITLE
Crashing again and again, And i am not able to find the solution for this..

### ISSUE THREAD

**Issue by AnupamKatiyar** [souzainf3/RNLoadingButton-Swift#18]
Please provide the solution asap. Thanks in advance

I am using it from Interface Builder

Simultaneous accesses to 0x108b34350, but modification requires exclusive access.
Previous access (a modification) started at ProFive`closure #1 in RNLoadingButton.awakeFromNib() + 656 (0x100848e70).
Current access (a read) started at:
0    libswiftCore.dylib                 0x000000010170da38 swift_beginAccess + 468
1    ProFive                            0x0000000100847b08 RNLoadingButton.titles.getter + 68
2    ProFive                            0x000000010084aa74 RNLoadingButton.title(for:) + 36
3    ProFive                            0x000000010084aae0 @objc RNLoadingButton.title(for:) + 60
4    UIKit                              0x000000018ab42ed0 <redacted> + 152
5    UIKit                              0x000000018ab45898 <redacted> + 56
6    UIKit                              0x000000018b520204 <redacted> + 188
7    UIKit                              0x000000018b520398 <redacted> + 1008
8    UIKit                              0x000000018b520398 <redacted> + 712
9    UIKit                              0x000000018b520398 <redacted> + 712
10   Foundation                         0x0000000181ff14f4 <redacted> + 168
11   UIKit                              0x000000018b520ec4 <redacted> + 92
12   UIKit                              0x000000018b51fa98 <redacted> + 116
13   UIKit                              0x000000018b520a94 <redacted> + 168
14   UIKit                              0x000000018b5219bc <redacted> + 428
15   UIKit                              0x000000018aa69834 <redacted> + 892
16   UIKit                              0x000000018aacef84 <redacted> + 100
17   ProFive                            0x000000010084ad3c RNLoadingButton.configureControl(for:) + 2972
18   ProFive                            0x000000010084d8c4 RNLoadingButton.store<A>(_:in:for:) + 720
19   ProFive                            0x0000000100848be0 closure #1 in RNLoadingButton.awakeFromNib() + 700
20   ProFive                            0x0000000100849024 thunk for @callee_owned (@unowned UIControlState) -> (@error @owned Error) + 36
21   ProFive                            0x000000010084c0f4 partial apply for thunk for @callee_owned (@unowned UIControlState) -> (@error @owned Error) + 96
22   libswiftCore.dylib                 0x0000000101623a78 specialized Collection.map<A>(_:) + 3168
23   libswiftCore.dylib                 0x000000010143c6ec Collection.map<A>(_:) + 24
24   ProFive                            0x00000001008489dc RNLoadingButton.awakeFromNib() + 440
25   ProFive                            0x00000001008490a0 @objc RNLoadingButton.awakeFromNib() + 40
26   UIKit                              0x000000018afcbfac <redacted> + 2136
27   UIKit                              0x000000018adbc6c8 <redacted> + 372
28   UIKit                              0x000000018ab766cc <redacted> + 176
29   UIKit                              0x000000018aa5755c <redacted> + 184
30   UIKit                              0x000000018aa57528 <redacted> + 28
31   UIKit                              0x000000018b5c0520 <redacted> + 92
32   UIKit                              0x000000018ad98354 <redacted> + 140
33   UIKit                              0x000000018adc596c <redacted> + 2676
34   UIKit                              0x000000018adc9298 <redacted> + 104
35   UIKit                              0x000000018adc9624 <redacted> + 528
36   UIKit                              0x000000018adc9194 <redacted> + 188
37   UIKit                              0x000000018ab371e8 <redacted> + 160
38   ProFive                            0x000000010088bb24 closure #2 in UserProfileVC.settingsButtonAction(_:) + 484
39   ProFive                            0x000000010088b9a0 thunk for @callee_owned (@owned UIAlertAction) -> () + 72
40   UIKit                              0x000000018af471e8 <redacted> + 108
41   UIKit                              0x000000018af47c30 <redacted> + 28
42   UIKit                              0x000000018ad98b38 <redacted> + 1320
43   UIKit                              0x000000018ad9c994 <redacted> + 188
44   UIKit                              0x000000018ab6a680 <redacted> + 116
45   UIKit                              0x000000018aa8f7e0 <redacted> + 764
46   UIKit                              0x000000018aa8f334 <redacted> + 312
47   UIKit                              0x000000018aa8f050 <redacted> + 296
48   UIKit                              0x000000018aa8f050 <redacted> + 456
49   QuartzCore                         0x0000000185696864 <redacted> + 284
50   libdispatch.dylib                  0x0000000101f8144c _dispatch_client_callout + 16
51   libdispatch.dylib                  0x0000000101f85ba8 _dispatch_main_queue_callback_4CF + 1192
52   CoreFoundation                     0x000000018166bf14 <redacted> + 12
53   CoreFoundation                     0x0000000181669320 <redacted> + 2012
54   CoreFoundation                     0x000000018158a124 CFRunLoopRunSpecific + 436
55   GraphicsServices                   0x000000018340ff20 GSEventRunModal + 100
56   UIKit                              0x000000018aabb510 UIApplicationMain + 208
57   ProFive                            0x000000010099e344 main + 76
58   libdyld.dylib                      0x00000001810ae568 <redacted> + 4

**Comment by souzainf3** [comment]
@AnupamKatiyar This is um open source project. You is free to modifier it.
I will stay happy with an pull request fixing it.
Before, see your code if you have any uncorrect  link with you Storyboard or XIB. Revise your code  and see has an incorrect modifiers for object.
More details of the error would help.
1. Whats version of  the Xcode
2. If the sample project of this repository have the same problem
3. Creating other project of test the project happens.

**Comment by AnupamKatiyar** [comment]
@souzainf3, Thanks for your response, I am using Xcode 9 GM Seed, and Swift 4, Same Issue is coming while setting up a new Xcode Project. Also your source code returning lots of layout engine crashes.

**Comment by souzainf3** [comment]
Fixed on version 5.0.0. Thanks @AnupamKatiyar.
