### ISSUE TITLE
The version on cocoaspod is still 0.0.1

### ISSUE THREAD

**Issue by shukaka** [souzainf3/RNLoadingButton-Swift#2]
The lastest version is 1.0.0, but while search on the pod , it is still 0.0.1 ,what's the problem ?

**Comment by souzainf3** [comment]
Hey @shukaka 
I am fixed it.

Version 0.0.1 - Write in Swift 1.0..
Version 2.0.1 - Swift 1.2;
Version 3.0.1 - Swift 2.x.
