### ISSUE TITLE
Xcode 10 compatibility - cocoapods

### ISSUE THREAD

**Issue by DavidCollinsNZ** [souzainf3/RNLoadingButton-Swift#21]
Anybody else having an issue with Xcode 10, follow the following steps to fix it:

1. In Xcode, go to File -> Project/Workspace settings.
2. Change the build system to Legacy Build system.

[https://stackoverflow.com/a/51089264/2356340](url)

**Comment by toddgower-hiatus** [comment]
I fixed this issue by going to Target -> RNLoadingButton-Swift -> Build Phases and removing Info.plist from the Compile Sources section. I couldn't use the Legacy Build system on our CI build server.

**Comment by DavidCollinsNZ** [comment]
> I fixed this issue by going to Target -> RNLoadingButton-Swift -> Build Phases and removing Info.plist from the Compile Sources section. I couldn't use the Legacy Build system on our CI build server.

Much better! Thanks for sharing

**Comment by toddgower-hiatus** [comment]
Can we get this fixed at the source? Don’t think the issue should be
closed until then.

In fact, it looks like there’s an open PR that addresses this.

**Comment by toddgower-hiatus** [comment]
After much wrangling, was able to figure out how to remove this via the cocoapod installation. Added the following to the end of my podfile:

    post_install do |installer_representation|

        if target.name=='RNLoadingButton-Swift'

          p target.source_build_phase.files_references
          target.source_build_phase.files_references.each do |file_ref|
            if file_ref.name == 'Info.plist'
              target.source_build_phase.remove_file_reference(file_ref)
            end
          end
          p target.source_build_phase.files_references
        end
      end
    end

**Comment by souzainf3** [comment]
I go update to fix it. Thanks.

**Comment by souzainf3** [comment]
@DavidCollinsNZ @toddgower Fixed in version 5.1.0.
