### ISSUE TITLE
Selector warnings

### ISSUE THREAD

**Issue by joshfuggle** [souzainf3/RNLoadingButton-Swift#7]
Hello,

When building via Carthage, I can see the following warnings:

`/Users/yongling/cachecart/14af1b1ca25de208511966aba291ffcf/a92d202117271be9c427c30cf2d2ce5e/Carthage/Checkouts/RNLoadingButton-Swift/RNLoadingButton/RNLoadingButton.swift:196:64: warning: use '#selector' instead of explicitly constructing a 'Selector'
/Users/yongling/cachecart/14af1b1ca25de208511966aba291ffcf/a92d202117271be9c427c30cf2d2ce5e/Carthage/Checkouts/RNLoadingButton-Swift/RNLoadingButton/RNLoadingButton.swift:196:64: warning: use '#selector' instead of explicitly constructing a 'Selector'
/Users/yongling/cachecart/14af1b1ca25de208511966aba291ffcf/a92d202117271be9c427c30cf2d2ce5e/Carthage/Checkouts/RNLoadingButton-Swift/RNLoadingButton/RNLoadingButton.swift:196:64: warning: use '#selector' instead of explicitly constructing a 'Selector'
/Users/yongling/cachecart/14af1b1ca25de208511966aba291ffcf/a92d202117271be9c427c30cf2d2ce5e/Carthage/Checkouts/RNLoadingButton-Swift/RNLoadingButton/RNLoadingButton.swift:196:64: warning: use '#selector' instead of explicitly constructing a 'Selector'`

**Comment by souzainf3** [comment]
Hey @josh-fuggle you can test again and send me an feedback?
