### ISSUE TITLE
How about Swift3.0 version

### ISSUE THREAD

**Issue by zzycami** [souzainf3/RNLoadingButton-Swift#8]
How about Swift3.0 version. We want a prev version. Soon will be coming

**Comment by souzainf3** [comment]
Version to Swift 3 is comming.

**Comment by joshfuggle** [comment]
Will you be supporting Swift 2.3 also?

**Comment by souzainf3** [comment]
The migration to swift 2.3 and 3.0 has completed.
Tanks @josh-fuggle and @zzycami
